apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name.db-name }}
  namespace: {{ .Values.name.namespace }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/db